trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pnpm_cache_directory: $(Pipeline.Workspace)/.pnpm-store

steps:
  - task: Cache@2
    inputs:
      key: pnpm | "$(Agent.OS)" | pnpm-lock.yaml
      path: $(pnpm_cache_directory)
    displayName: "Cache pnpm store"

  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_cache_directory)
    displayName: "pnpm setup"

  - script: pnpm install
    displayName: "pnpm install"

  - script: pnpm build
    displayName: "pnpm build"
