trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pnpm_cache_directory: $(Pipeline.Workspace)/.pnpm-store


stages:
  - stage: build
    displayName: "Build"
    jobs:
      - job: build
        steps:
          - task: Cache@2
            inputs:
              key: pnpm | "$(Agent.OS)" | pnpm-lock.yaml
              path: $(pnpm_cache_directory)
            displayName: "Cache pnpm store"

          - script: |
              corepack enable
              corepack prepare pnpm@latest-8 --activate
              pnpm config set store-dir $(pnpm_cache_directory)
            displayName: "pnpm setup"

          - script: pnpm install

          - script: pnpm build

  - stage: docker_build
    displayName: "Docker build"
    jobs:
      - job: docker_build
        steps:
          - task: Docker@2
            inputs:
              command: build
              tags: |
                latest
                $(Build.BuildId)
            displayName: "Docker build"
