steps:
  - name: 'node:20-alpine'
    script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm install
      pnpm build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', $_IMAGE_TAG , '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', $_IMAGE_TAG ]

substitutions:
  _IMAGE_TAG: europe-west1-docker.pkg.dev/$PROJECT_ID/techno-gallery/$REPO_NAME:$COMMIT_SHA
