steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: [ 'build', '-t', $_IMAGE_LATEST, '-t', $_IMAGE_SHA, '--cache-from', $_IMAGE_LATEST ,  '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args: [ 'push', '--all-tags', $_IMAGE ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    id: 'gcloud-run-deploy'
    args: [ 'run', 'deploy', $_SERVICE_NAME, '--image', $_IMAGE_SHA, '--region', $_REGION, '--allow-unauthenticated', '--min-instances', '0', '--max-instances', '2',  '--memory', '512Mi', '--cpu', '1', '--timeout', '30s', '--concurrency', '80' ]

images:
  - $_IMAGE_LATEST
  - $_IMAGE_SHA

substitutions:
  _SERVICE_NAME: $REPO_NAME
  _REGION: europe-west1
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/techno-gallery/${_SERVICE_NAME}
  _IMAGE_LATEST: ${_IMAGE}:latest
  _IMAGE_SHA: ${_IMAGE}:${SHORT_SHA}
