steps:
  - name: 'node:20-alpine'
    id: 'pnpm-build'
    script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm install
      pnpm build

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '-t', $_IMAGE_TAG , '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args: ['push', $_IMAGE_TAG ]

images:
  - $_IMAGE_TAG

substitutions:
  _SERVICE_NAME: $REPO_NAME
  _IMAGE_TAG: europe-west1-docker.pkg.dev/${PROJECT_ID}/techno-gallery/${_SERVICE_NAME}:${COMMIT_SHA}
